//
//  VenueInteractor.swift
//  VenueList
//
//  Created by Erva Hatun Tekeoğlu on 29.12.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol VenueBusinessLogic {
    func fetchVenues(request: Venue.FetchVenue.Request, radius: String?, lon: String, lat: String)
}

class VenueInteractor: VenueBusinessLogic/*, VenueDataStore*/ {
    var presenter: VenuePresentationLogic?
    var worker: VenueWorker? = VenueWorker()

    
    func fetchVenues(request: Venue.FetchVenue.Request, radius: String?, lon: String, lat: String ) {
        worker = VenueWorker()
        
        //"37.33", longitude: lon ?? "-121.88"
        worker?.fetchVenues(latitude: lat, longitude: lon, radius: radius ?? "10000") { (data,error)  in
        if error == nil, let welcome = data {
                let response = Venue.FetchVenue.Response(welcome: welcome)
                self.presenter?.presentVenues(response: response)
            } else {
                if let error = error {
                    self.presenter?.presentError(error: "Give radious between 1 and 10000.")
                }
            }
        }
    }
}
