//
//  VenueRouter.swift
//  VenueList
//
//  Created by Erva Hatun Tekeoğlu on 29.12.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol VenueRoutingLogic {
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol VenueDataPassing {
  //var dataStore: VenueDataStore? { get }
}

class VenueRouter: NSObject, VenueRoutingLogic, VenueDataPassing {
  weak var viewController: VenueViewController?
  
}
