//
//  VenueModels.swift
//  VenueList
//
//  Created by Erva Hatun Tekeoğlu on 29.12.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Venue {
  // MARK: Use cases
  
  enum FetchVenue {
    struct Request {
    }
    struct Response {
        var welcome: Welcome
    }
    struct ViewModel {
        struct DisplayedVenues {
            var type: String? 
            var id: String?
            var score, dist: Double?
            var info: String?
            var address: Address
            var position: GeoBias
            var poi: Poi
        }
    
        var displayedVenues: [Venue.FetchVenue.ViewModel.DisplayedVenues]?
    }
  }
}
